      "data-component-path": "src/App.tsx",
      "data-component-line": "15",
      "data-component-file": "App.tsx",
      "data-component-name": "QueryClientProvider",
      "data-component-content": "%7B%7D",
      client: LT,
      children: d.jsx(hP, {
        "data-lov-id": "src/App.tsx:16:4",
        "data-lov-name": "TooltipProvider",
        "data-component-path": "src/App.tsx",
        "data-component-line": "16",
        "data-component-file": "App.tsx",
        "data-component-name": "TooltipProvider",
        "data-component-content": "%7B%7D",
        children: d.jsx(I_, {
          "data-lov-id": "src/App.tsx:17:6",
          "data-lov-name": "BrowserRouter",
          "data-component-path": "src/App.tsx",
          "data-component-line": "17",
          "data-component-file": "App.tsx",
          "data-component-name": "BrowserRouter",
          "data-component-content": "%7B%7D",
          children: d.jsxs(fI, {
            "data-lov-id": "src/App.tsx:18:8",
            "data-lov-name": "AuthProvider",
            "data-component-path": "src/App.tsx",
            "data-component-line": "18",
            "data-component-file": "App.tsx",
            "data-component-name": "AuthProvider",
            "data-component-content": "%7B%7D",
            children: [
              d.jsxs(E_, {
                "data-lov-id": "src/App.tsx:19:10",
                "data-lov-name": "Routes",
                "data-component-path": "src/App.tsx",
                "data-component-line": "19",
                "data-component-file": "App.tsx",
                "data-component-name": "Routes",
                "data-component-content": "%7B%7D",
                children: [
                  d.jsx(fi, {
                    "data-lov-id": "src/App.tsx:20:12",
                    "data-lov-name": "Route",
                    "data-component-path": "src/App.tsx",
                    "data-component-line": "20",
                    "data-component-file": "App.tsx",
                    "data-component-name": "Route",
                    "data-component-content": "%7B%7D",
                    path: "/",
                    element: d.jsx(OT, {
                      "data-lov-id": "src/App.tsx:20:37",
                      "data-lov-name": "Index",
                      "data-component-path": "src/App.tsx",
                      "data-component-line": "20",
                      "data-component-file": "App.tsx",
                      "data-component-name": "Index",
                      "data-component-content": "%7B%7D",
                    }),
                  }),
                  d.jsx(fi, {
                    "data-lov-id": "src/App.tsx:21:12",
                    "data-lov-name": "Route",
                    "data-component-path": "src/App.tsx",
                    "data-component-line": "21",
                    "data-component-file": "App.tsx",
                    "data-component-name": "Route",
                    "data-component-content": "%7B%7D",
                    path: "/auth",
                    element: d.jsx(BT, {
                      "data-lov-id": "src/App.tsx:21:41",
                      "data-lov-name": "AuthPage",
                      "data-component-path": "src/App.tsx",
                      "data-component-line": "21",
                      "data-component-file": "App.tsx",
                      "data-component-name": "AuthPage",
                      "data-component-content": "%7B%7D",
                    }),
                  }),
                  d.jsx(fi, {
                    "data-lov-id": "src/App.tsx:25:12",
                    "data-lov-name": "Route",
                    "data-component-path": "src/App.tsx",
                    "data-component-line": "25",
                    "data-component-file": "App.tsx",
                    "data-component-name": "Route",
                    "data-component-content": "%7B%7D",
                    path: "*",
                    element: d.jsx(IT, {
                      "data-lov-id": "src/App.tsx:25:37",
                      "data-lov-name": "NotFound",
                      "data-component-path": "src/App.tsx",
                      "data-component-line": "25",
                      "data-component-file": "App.tsx",
                      "data-component-name": "NotFound",
                      "data-component-content": "%7B%7D",
                    }),
                  }),
                ],
              }),
              d.jsx(hA, {
                "data-lov-id": "src/App.tsx:27:10",
                "data-lov-name": "Toaster",
                "data-component-path": "src/App.tsx",
                "data-component-line": "27",
                "data-component-file": "App.tsx",
                "data-component-name": "Toaster",
                "data-component-content": "%7B%7D",
              }),
            ],
          }),
        }),
      }),
    });
Zv(document.getElementById("root")).render(
  d.jsx($T, {
    "data-lov-id": "src/main.tsx:5:52",
    "data-lov-name": "App",
